language: node_js
node_js: stable

jobs:
  include:
    - stage: test
      name: "Unit tests, type checking, linting, etc."
      script:
        - yarn run check-types
        - yarn test
    - stage: release
      name: "Release on npm (if necessary)"
      deploy:
        provider: script
        skip_cleanup: true
        script:
          - yarn semantic-release