language: node_js
node_js:
  - stable
install:
  - yarn install
script:
  - yarn run check-types
  - yarn test

jobs:
  include:
    - stage: release
      deploy:
        provider: script
        skip_cleanup: true
        script:
          - npx semantic-release
